dataset_name: "mc_question_val"
task: "perceptiontest_val_mc"
test_split: validation
output_type: generate_until
doc_to_visual: !function utils.perceptiontest_val_doc_to_visual
doc_to_text: !function utils.perceptiontest_val_doc_to_text
doc_to_target: !function utils.perceptiontest_val_doc_to_answer
process_results: !function utils.perceptiontest_val_process_results_mc
metric_list:
  - metric: accuracy
    aggregation: !function utils.perceptiontest_val_aggregate_accuracy
    higher_is_better: true
dataset_path: parquet
dataset_kwargs:
  token: True
  video: True
  cache_dir: perceptiontest_val
  data_files:
    validation: /workspace/group_share/adc-perception-xplanner/songsy/evaluate_datasets/hub/datasets--lmms-lab--PerceptionTest_Val/snapshots/c5e520d8c4167fb1f135c36e9d6e67312b4f8e6b/mc_question_val/*.parquet
lmms_eval_specific_kwargs:
  default:
    pre_prompt: "Select the best answer to the following multiple-choice question based on the video.\n"
    post_prompt: ""
