task: "nextqa_mc_test"
dataset_name: MC
test_split: test
output_type: generate_until
doc_to_visual: !function utils.nextqa_doc_to_visual
doc_to_text: !function utils.nextqa_doc_to_text_mc
doc_to_target: !function utils.nextqa_doc_to_target
process_results: !function utils.nextqa_mc_process_results
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
dataset_path: parquet
dataset_kwargs:
  token: True
  video: True
  cache_dir: nextqa
  data_files:
    test:
      /workspace/group_share/adc-perception-xplanner/songsy/evaluate_datasets/hub/datasets--lmms-lab--NExTQA/snapshots/a0d7729e38399da9c8a70c59aa4ad7f6996d3c00/MC/*.parquet
metadata:
  version: 0.0.1
  load_package: False
