dataset_path: /workspace/group_share/adc-perception-xplanner/songsy/evaluate_datasets/hub/datasets--longvideobench--LongVideoBench/snapshots/60d1c89c1919a198b73be39c2babb213b29d6a5c
dataset_kwargs:
  token: True
  cache_dir: longvideobench
  video: True
  force_download: False
  local_files_only: True
  # From_YouTube: True
task: longvideobench_val_v
test_split: validation
doc_to_visual: !function utils.longvideobench_doc_to_visual_v
doc_to_text: !function utils.longvideobench_doc_to_text
doc_to_target: "correct_choice"
generation_kwargs:
  max_new_tokens: 32
  temperature: 0
  do_sample: False
process_results: !function utils.longvideobench_process_results
metric_list:
  - metric: lvb_acc
    aggregation: !function utils.longvideobench_aggregate_results
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    pre_prompt: "Select the best answer to the following multiple-choice question based on the video.\n"
    post_prompt: "Answer with the option's letter from the given choices directly.\n"
  