task: "activitynetqa"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.activitynetqa_doc_to_visual
doc_to_text: !function utils.activitynetqa_doc_to_text
doc_to_target: !function utils.activitynetqa_doc_to_answer
process_results: !function utils.activitynetqa_process_results # gpt eval here for each QA pairs
metric_list:
  - metric: gpt_eval_score
    aggregation: !function utils.activitynetqa_aggregate_score # parse scores from each QA pairs
    higher_is_better: true
  - metric: gpt_eval_accuracy
    aggregation: !function utils.activitynetqa_aggregate_accuracy # parse accuracy from each QA pairs
    higher_is_better: true

dataset_path: /workspace/group_share/adc-perception-xplanner/songsy/evaluate_datasets/hub/datasets--lmms-lab--ActivityNetQA/snapshots/83e5a35a25748273ffcff353f161949b486925a9
dataset_kwargs:
  token: True
  video: True
  force_download: False
  local_files_only: False
  cache_dir: activitynetqa
  data_files:
    test: /workspace/group_share/adc-perception-xplanner/songsy/evaluate_datasets/hub/datasets--lmms-lab--ActivityNetQA/snapshots/83e5a35a25748273ffcff353f161949b486925a9/data/*.parquet
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: " Answer the question using a single word or phrase."

metadata:
  version: 0.0
  gpt_eval_model_name: gpt-3.5-turbo-1106

generation_kwargs:
  until:
    - "ASSISTANT:"
  image_aspect_ratio: original
  max_new_tokens: 64
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
