dataset_name: "Subset"
task: "egoschema_subset_mcppl"
test_split: test
output_type: multiple_choice
doc_to_visual: !function utils.egoschema_doc_to_visual
doc_to_text: "question"
doc_to_target: !function utils.egoschema_doc_to_answer
doc_to_choice: !function utils.egoschema_doc_to_choice
process_results: !function utils.egoschema_process_results
metric_list:
  - metric: submission
    aggregation: !function utils.egoschema_aggregate_mc_ppl
    higher_is_better: true
  - metric: score
    aggregation: !function utils.egoschema_aggregate_score
    higher_is_better: true
dataset_path: /workspace/group_share/adc-perception-xplanner/songsy/evaluate_datasets/hub/datasets--lmms-lab--egoschema/snapshots/58350524ea7eb29c47000121f4f4b65eb6b4acb9
dataset_kwargs:
  token: True
  video: True
  cache_dir: egoschema
  data_files:
    test: /workspace/group_share/adc-perception-xplanner/songsy/evaluate_datasets/hub/datasets--lmms-lab--egoschema/snapshots/58350524ea7eb29c47000121f4f4b65eb6b4acb9/MC/.parquet
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
