dataset_name: "Subset"
task: "egoschema_subset"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.egoschema_doc_to_visual
doc_to_text: !function utils.egoschema_doc_to_text
doc_to_target: !function utils.egoschema_doc_to_answer
process_results: !function utils.egoschema_process_results_generation
metric_list:
  - metric: submission
    aggregation: !function utils.egoschema_aggregate_mc
    higher_is_better: true
  - metric: score
    aggregation: !function utils.egoschema_aggregate_score
    higher_is_better: true
dataset_path: /workspace/group_share/adc-perception-xplanner/songsy/evaluate_datasets/hub/datasets--lmms-lab--egoschema/snapshots/58350524ea7eb29c47000121f4f4b65eb6b4acb9
dataset_kwargs:
  token: True
  video: True
  cache_dir: egoschema
  data_files:
    test: /workspace/group_share/adc-perception-xplanner/songsy/evaluate_datasets/hub/datasets--lmms-lab--egoschema/snapshots/58350524ea7eb29c47000121f4f4b65eb6b4acb9/Subset/*.parquet

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
